import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey } from "@solana/web3.js";
import fs from "fs";
import path from "path";
import { connection, loadOracleKeypair, PROGRAM_ID } from "./config";

/**
 * Build the Anchor program client using the IDL generated by `anchor build`
 * (target/idl/safexbets.json). The oracle keypair is the provider wallet — it is
 * the market authority that may accrue yield and settle.
 */
export function getProgram() {
  const wallet = new anchor.Wallet(loadOracleKeypair());
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });
  const idlPath = path.resolve(process.cwd(), "../target/idl/safexbets.json");
  if (!fs.existsSync(idlPath)) {
    throw new Error(
      `IDL not found at ${idlPath}. Run \`anchor build\` on the Mac first (see docs/MAC-SETUP.md §4).`
    );
  }
  const idl = JSON.parse(fs.readFileSync(idlPath, "utf-8"));
  const program = new Program(idl as anchor.Idl, provider);
  return { program, provider, wallet };
}

export function marketPda(matchId: anchor.BN): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("market"), matchId.toArrayLike(Buffer, "le", 8)],
    PROGRAM_ID
  )[0];
}

export function vaultPda(market: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), market.toBuffer()],
    PROGRAM_ID
  )[0];
}
